/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seleuco_xpectrum_Emulator */

#ifndef _Included_com_seleuco_xpectrum_Emulator
#define _Included_com_seleuco_xpectrum_Emulator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seleuco_xpectrum_Emulator
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_seleuco_xpectrum_Emulator_init
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_seleuco_xpectrum_Emulator
 * Method:    pauseEmulation
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_seleuco_xpectrum_Emulator_pauseEmulation
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_seleuco_xpectrum_Emulator
 * Method:    setPadData
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_seleuco_xpectrum_Emulator_setPadData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_seleuco_xpectrum_Emulator
 * Method:    isEmulatorInInnerMenu
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_seleuco_xpectrum_Emulator_isEmulatorInInnerMenu
  (JNIEnv *, jclass);

/*
 * Class:     com_seleuco_xpectrum_Emulator
 * Method:    enabledExternalKeyboard
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_seleuco_xpectrum_Emulator_enabledExternalKeyboard
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_seleuco_xpectrum_Emulator
 * Method:    setKeys
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_com_seleuco_xpectrum_Emulator_setKeys
  (JNIEnv *, jclass, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
